[package]
name = "nimiq-tree"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Patricia Merkle tree primitives for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
hex = "0.4"

beserial = { path = "../../beserial" }
beserial_derive = { path = "../../beserial/beserial_derive" }
nimiq-account = { path = "../account" }
nimiq-hash = { path = "../../hash" }
nimiq-keys = { path = "../../keys" }

[dev-dependencies]
nimiq-primitives = { path = "../../primitives", features = ["coin"] }
nimiq-transaction = { path = "../transaction" }
