version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  groups:
    minor-and-patch-updates:
    applies-to: version-updates
    update-types:
    - "minor"
    - "patch"
  schedule:
    interval: daily
    timezone: America/Costa_Rica
  open-pull-requests-limit: 10
  reviewers:
  - jsdanielh
  assignees:
  - jsdanielh
- package-ecosystem: cargo
  directory: "/"
  groups:
    minor-and-patch-updates:
    applies-to: version-updates
    update-types:
    - "minor"
    - "patch"
  schedule:
    interval: daily
    timezone: America/Costa_Rica
  open-pull-requests-limit: 10
  reviewers:
  - jsdanielh
  assignees:
  - jsdanielh
