[network]
peer_key_file = "temp-state/dev/1/peer_key.dat"
listen_addresses = [
	"/ip4/127.0.0.1/tcp/9101/ws",
]
seed_nodes = [
	{ address = "/ip4/127.0.0.1/tcp/9102/ws" }
]
min_peers = 1

[consensus]
network = "dev-albatross"
min_peers = 1

[database]
path = "temp-state/dev/1"

[log]
level = "trace"
timestamps = true

[validator]
validator_key_file = "temp-state/dev/1/validator_key.dat"
validator_key = "196ffdb1a8acc7cbd76a251aeac0600a1d68b3aba1eba823b5e4dc5dbdcdc730afa752c05ab4f6ef8518384ad514f403c5a088a22b17bf1bc14f8ff8decc2a512c0a200f68d7bdf5a319b30356fe8d1d75ef510aed7a8660968c216c328a0000"
cold_key_file = "temp-state/dev/1/cold_key.dat"
warm_key_file = "temp-state/dev/1/warm_key.dat"