[package]
name = "nimiq-block-albatross"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Block primitives for Albatross"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
failure = "0.1"
hex = "0.4"
log = "0.4"
num-bigint = "0.2"

beserial = { path = "../../beserial", version = "0.1" }
beserial_derive = { path = "../../beserial/beserial_derive", version = "0.1" }
nimiq-account = { path = "../account", version = "0.1" }
nimiq-block-base = { path = "../block-base", version = "0.1" }
nimiq-bls = { path = "../../bls", version = "0.1", features = ["beserial"]}
nimiq-collections = { path = "../../collections", version = "0.1", features = ["bitset"] }
nimiq-hash = { path = "../../hash", version = "0.1" }
nimiq-hash_derive = { path = "../../hash/hash_derive", version = "0.1" }
nimiq-keys = { path = "../../keys", version = "0.1" }
nimiq-macros = { path = "../../macros", version = "0.1" }
nimiq-primitives = { path = "..", version = "0.1", features = ["policy", "networks"] }
nimiq-transaction = { path = "../transaction", version = "0.1" }
nimiq-utils = { path = "../../utils", version = "0.1", features = ["merkle"] }
nimiq-vrf = { path = "../../vrf", version = "0.1" }

[dev-dependencies]
num-traits = "0.2"
