[package]
name = "nimiq-genesis-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
log = { package = "tracing", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
time = { version = "0.3", features = ["parsing"] }
toml = "0.7"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

beserial = { path = "../beserial" }
nimiq-account = { path = "../primitives/account" }
nimiq-block = { path = "../primitives/block" }
nimiq-bls = { path = "../bls" }
nimiq-database = { path = "../database" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-vrf = { path = "../vrf" }
