[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "history"

[[validator]]
restartable = true
sync_mode = "history"

[[validator]]
restartable = true
sync_mode = "history"

[[validator]]
restartable = true
sync_mode = "history"

[[spammer]]
restartable = false
sync_mode = "history"
tpb = 700

[[seed]]
restartable = false
sync_mode = "history"

[[node]]
restartable = false
sync_mode = "light"
