[network]
peer_key_file = "/home/nimiq/peer_key.dat"
listen_addresses = [
    "/ip4/0.0.0.0/tcp/8443/ws",
]
advertised_addresses = [
    "/dns4/validator2/tcp/8443/ws", # Docker-internal
    "/dns4/validator2.nimiq.local/tcp/8502/ws" # Docker-external
]

seed_nodes = [
        { address = "/dns4/seed1/tcp/8443/ws" }
]

[consensus]
network = "dev-albatross"
sync_mode = "history"
min_peers = 3

[database]
path = "/home/nimiq"

[log]
level = "info"
timestamps = true

# [log.tags]
# libp2p_swarm = "debug"
# lock_api = "trace"

[validator]
validator_address = "NQ63 LUQD 0KAU V52T EBV9 LQ2B H8TX 7B53 Y55F"
signing_key_file = "/home/nimiq/signing_key.dat"
signing_key = "862b6e5897435e5afc0df047602a272833a8de0a1e5f48dcd1015a846cb64a30"
voting_key_file = "/home/nimiq/voting_key.dat"
voting_key = "b1c907911c73b5e1e635b39d1b3f5e5bd108f7c193e1ca4dd25be9550eef434814d63a86a5ba4c0dfe8977cbb153ba25c407a6c97a97866fba63c133ebdf441269444347c5e21523dbcf0c1a5135e710d60407e59db1e9315b81c895833c01"
fee_key_file = "/home/nimiq/fee_key.dat"
fee_key = "a170413f9c8dbca17522fcbe7a80eaa7821f9866cd41a89c275d4fa7f1718f82"
