[package]
name = "nimiq-network-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Network primitives and constants for Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
bitflags = "1.0"
hex = "0.3"
lazy_static = "1.2"
atomic = "0.4"
url = "1.7"
failure = "0.1"
beserial = { path = "../beserial", version = "0.1.0" }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1.0" }
nimiq-keys = { path = "../keys", version = "0.1.0" }
nimiq-hash = { path = "../hash", version = "0.1.0" }
nimiq-block = { path = "../primitives/block", version = "0.1.0" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1.0" }
nimiq-primitives = { path = "../primitives", version = "0.1.0", features = ["coin", "networks"] }
nimiq-utils = { path = "../utils", version = "0.1.0", features = ["observer", "crc", "time"] }
nimiq-macros = { path = "../macros", version = "0.1.0" }

[features]
default = ["all"]
all = ["networks", "time", "address", "services", "version", "protocol", "subscription"]
networks = ["address", "services", "protocol"]
time = []
address = ["services", "protocol"]
services = []
version = []
protocol = []
subscription = []
