[package]
name = "nimiq-hash"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Common wrapper around hash implementations used in Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
blake2-rfc = "0.2"
hex = "0.3"
sha2 = "0.8"
byteorder = "1.2"
beserial = { path = "../beserial", version = "0.1" }
nimiq-macros = { path = "../macros", version = "0.1" }
libargon2-sys = { path = "../libargon2-sys", version = "0.1" }
