[package]
name = "nimiq-nano-blockchain"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Block storage for Nimiq's Nano Nodes"
license = "Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2018"

[dependencies]
nimiq-block-albatross = { path = "../primitives/block-albatross" }
nimiq-genesis = { path = "../genesis" }
nimiq-hash = { path = "../hash" }
nimiq-primitives = { path = "../primitives" }
nimiq-nano-sync = { path = "../nano-sync", default-features = false, features = ["verifier"]  }