[package]
name = "nimiq-nano-blockchain"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Block storage for Nimiq's Nano Nodes"
license = "Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2018"

[dependencies]
thiserror = "1.0"

nimiq-account = { path = "../primitives/account" }
nimiq-block = { path = "../primitives/block" }
nimiq-blockchain = { path = "../blockchain" }
nimiq-database = { path = "../database" }
nimiq-genesis = { path = "../genesis" }
nimiq-hash = { path = "../hash" }
nimiq-nano-zkp = { path = "../nano-zkp" }
nimiq-primitives = { path = "../primitives", features = ["policy"] }
nimiq-tree = { path = "../primitives/tree" }
nimiq-utils = { path = "../utils", features = ["time"] }

[dev-dependencies]
rand = "^0.8"

nimiq-block-production = { path = "../block-production", features = ["test-utils"] }