[package]
name = "nimiq-ws-rpc-server"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "Websocket RPC server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
failure = "0.1"
futures = "0.3"
json = "0.12"
log = "0.4"
parking_lot = "0.9"
tokio = "0.2"
tokio-tungstenite = { git = "https://github.com/snapview/tokio-tungstenite" }

nimiq-block-albatross = { path = "../primitives/block-albatross", version = "0.1" }
nimiq-blockchain-albatross = { path = "../blockchain-albatross", version = "0.1" }
nimiq-blockchain-base = { path = "../blockchain-base", version = "0.1" }
nimiq-bls = { path = "../bls", version = "0.1", optional = true }
nimiq-consensus = { path = "../consensus", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-mempool = { path = "../mempool", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["unique-id"] }
nimiq-validator = { path = "../validator", version = "0.1", optional = true }

[features]
validator = ["nimiq-validator"]
