[package]
name = "nimiq-block"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Block primitives to be used in Nimiq's Albatross implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
bitflags = "1.0"
thiserror = "1.0"
hex = "0.4"
log = "0.4"
num-bigint = "0.4.2"
serde = { version = "1.0", features = ["derive"], optional = true }

beserial = { path = "../../beserial" }
beserial_derive = { path = "../../beserial/beserial_derive" }
nimiq-bls = { path = "../../bls", features = ["beserial"]}
nimiq-collections = { path = "../../collections", features = ["bitset"] }
nimiq-database = { path = "../../database" }
nimiq-handel = { path = "../../handel" }
nimiq-hash = { path = "../../hash" }
nimiq-hash_derive = { path = "../../hash/hash_derive" }
nimiq-keys = { path = "../../keys" }
nimiq-macros = { path = "../../macros" }
nimiq-nano-primitives = { path = "../../nano-primitives" }
nimiq-primitives = { path = "..", features = ["policy", "networks", "coin", "slots"] }
nimiq-transaction = { path = "../transaction" }
nimiq-utils = { path = "../../utils", features = ["merkle"] }
nimiq-vrf = { path = "../../vrf" }

[dev-dependencies]
num-traits = "0.2"

[features]
serde-derive = ["serde", "nimiq-collections/serde-derive", "nimiq-bls/serde-derive"]
