[package]
name = "nimiq-block"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Block primitives to be used in Nimiq's Albatross implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
ark-ec = "0.4"
bitflags = { version = "2.6", features = ["serde"] }
byteorder = "1.5"
hex = "0.4"
log = { workspace = true }
serde = "1.0"
serde_repr = "0.1"
thiserror = "1.0"

nimiq-bls = { workspace = true, features = ["cache", "serde-derive"]}
nimiq-collections = { workspace = true }
nimiq-database-value = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-hash_derive = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-macros = { workspace = true }
nimiq-network-interface = { workspace = true }
nimiq-primitives = { workspace = true, features = ["coin", "networks", "policy", "slots", "tendermint"] }
nimiq-serde = { workspace = true }
nimiq-transaction = { workspace = true }
nimiq-utils = { workspace = true, features = ["merkle"] }
nimiq-vrf = { workspace = true, features = ["serde-derive"] }

[dev-dependencies]
nimiq-handel = { workspace = true }
nimiq-test-log = { workspace = true }
nimiq-test-utils = { workspace = true }
