[package]
name = "nimiq-block"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Block primitives to be used in Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
num-bigint = "0.2"
log = "0.4"
hex = "0.3"
beserial = { path = "../../beserial", version = "0.1.0" }
beserial_derive = { path = "../../beserial/beserial_derive", version = "0.1.0" }
fixed-unsigned = { path = "../../fixed-unsigned", version = "0.1.0" }
nimiq-hash = { path = "../../hash", version = "0.1.0" }
nimiq-keys = { path = "../../keys", version = "0.1.0" }
nimiq-utils = { path = "../../utils", version = "0.1.0", features = ["merkle"] }
nimiq-primitives = { path = "..", version = "0.1.0", features = ["policy", "networks"] }
nimiq-transaction = { path = "../transaction", version = "0.1.0" }
nimiq-account = { path = "../account", version = "0.1.0" }
nimiq-macros = { path = "../../macros", version = "0.1.0" }

[dev-dependencies]
num-traits = "0.2"
