[package]
name = "nimiq-zkp-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2021"

[dependencies]
ark-crypto-primitives = { version = "0.4", features = ["crh"] }
ark-ec = "0.4"
ark-ff = "0.4"
ark-groth16 = { version = "0.4", default-features = false }
ark-mnt4-753 = "0.4"
ark-mnt6-753 = "0.4"
ark-relations = "0.4"
ark-r1cs-std = "0.4"
ark-serialize = "0.4"
ark-std = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
num-traits = "0.2"
rand = { version = "0.8", features = ["small_rng"] }
rayon = { version = "^1.7", optional = true }
thiserror = "1.0"

beserial = { path = "../beserial", features = ["derive"] }
nimiq-bls = { path = "../bls" }
nimiq-hash = { path = "../hash" }
nimiq-pedersen-generators = { path = "pedersen-generators" }
nimiq-primitives = { path = "../primitives", features = ["policy"] }

hex = "0.4"

[dev-dependencies]
nimiq-block = { path = "../primitives/block" }
nimiq-collections = { path = "../collections" }
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives", features = ["slots"] }
nimiq-test-log = { path = "../test-log" }
nimiq-test-utils = { path = "../test-utils" }
nimiq-utils = { path = "../utils" }

[features]
parallel = ["rayon", "ark-ec/parallel", "ark-ff/parallel", "ark-std/parallel", "ark-groth16/parallel"]
zkp-prover = ["ark-mnt4-753/r1cs", "ark-mnt6-753/r1cs", "ark-groth16/r1cs"]
