[package]
name = "nimiq-zkp-prove"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Binary to generate 2 consecutive proofs."
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
clap = { version = "4.5", features = ["cargo", "string", "derive"] }
hex = "0.4"
log = { workspace = true }
parking_lot = "0.12"
serde = "1.0"
tokio = { version = "1.39", features = ["macros", "rt", "sync"] }
tracing-subscriber = { version = "0.3" }

nimiq-block = { workspace = true }
nimiq-blockchain = { workspace = true }
nimiq-blockchain-interface = { workspace = true }
nimiq-blockchain-proxy = { workspace = true }
nimiq-database = { workspace = true }
nimiq-genesis = { workspace = true }
nimiq-log = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy"] }
nimiq-serde = { workspace = true }
nimiq-test-utils = { workspace = true }
nimiq-utils = { workspace = true, features = ["time"] }
nimiq-zkp = { workspace = true, features = ["zkp-prover"] }
nimiq-zkp-circuits = { workspace = true, features = ["zkp-prover"] }
nimiq-zkp-component = { workspace = true, features = ["zkp-prover"] }
nimiq-zkp-primitives = { workspace = true, features = ["zkp-prover"] }
