[package]
name = "nimiq-test-utils"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2021"
description = "Test utilities for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[dependencies]
async-trait = "0.1"
futures = { package = "futures-util", version = "0.3" }
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
rand = "0.8"
parking_lot = { git = "https://github.com/styppo/parking_lot.git" }
tokio = { version = "1.24", features = ["rt", "time", "tracing"] }
tokio-stream = "0.1"
rand_chacha = "0.3.1"

beserial = { path = "../beserial" }
nimiq-account = { path = "../primitives/account" }
nimiq-block = { path = "../primitives/block" }
nimiq-blockchain = { path = "../blockchain" }
nimiq-blockchain-interface = { path = "../blockchain-interface" }
nimiq-blockchain-proxy = { path = "../blockchain-proxy" }
nimiq-block-production = { path = "../block-production" }
nimiq-bls = { path = "../bls" }
nimiq-collections = { path = "../collections" }
nimiq-consensus = { path = "../consensus" }
nimiq-database = { path = "../database" }
nimiq-genesis = { path = "../genesis" }
nimiq-genesis-builder = { path = "../genesis-builder" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-mempool = { path = "../mempool" }
nimiq-nano-primitives = { path = "../nano-primitives" }
nimiq-transaction-builder = { path = "../transaction-builder" }
nimiq-trie = { path = "../primitives/trie" }
nimiq-network-interface = { path = "../network-interface" }
nimiq-network-libp2p = { path = "../network-libp2p" }
nimiq-network-mock = { path = "../network-mock" }
nimiq-primitives = { path = "../primitives" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-validator = { path = "../validator" }
nimiq-validator-network = { path = "../validator-network" }
nimiq-utils = { path = "../utils" }
nimiq-vrf = { path = "../vrf" }
nimiq-zkp-component = { path = "../zkp-component", features = ["zkp-prover", "zkp-storage"] }
