[package]
name = "nimiq-test-utils"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Test utilities for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
ark-ff = "0.4"
ark-groth16 = { version = "0.4", default-features = false }
ark-mnt6-753 = "0.4"
ark-serialize = "0.4"
async-trait = "0.1"
futures = { package = "futures-util", version = "0.3" }
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
num-traits = "0.2"
parking_lot = "0.12"
paste = "1.0"
rand = "0.8"
rand_chacha = "0.3.1"
serde = "1.0"
tokio = { version = "1.29", features = ["rt", "time", "tracing"] }
tokio-stream = "0.1"

nimiq-account = { path = "../primitives/account" }
nimiq-block = { path = "../primitives/block" }
nimiq-blockchain = { path = "../blockchain" }
nimiq-blockchain-interface = { path = "../blockchain-interface" }
nimiq-blockchain-proxy = { path = "../blockchain-proxy" }
nimiq-block-production = { path = "../block-production" }
nimiq-bls = { path = "../bls" }
nimiq-collections = { path = "../collections" }
nimiq-consensus = { path = "../consensus" }
nimiq-database = { path = "../database" }
nimiq-genesis = { path = "../genesis" }
nimiq-genesis-builder = { path = "../genesis-builder" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-mempool = { path = "../mempool" }
nimiq-network-interface = { path = "../network-interface" }
nimiq-network-libp2p = { path = "../network-libp2p" }
nimiq-network-mock = { path = "../network-mock" }
nimiq-primitives = { path = "../primitives" }
nimiq-serde = { path = "../serde" }
nimiq-tendermint = { path = "../tendermint" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-transaction-builder = { path = "../transaction-builder" }
nimiq-trie = { path = "../primitives/trie" }
nimiq-validator = { path = "../validator" }
nimiq-validator-network = { path = "../validator-network" }
nimiq-utils = { path = "../utils" }
nimiq-vrf = { path = "../vrf" }
nimiq-zkp-circuits = { path = "../zkp-circuits", features = ["test-setup", "zkp-prover", "parallel"] }
nimiq-zkp-component = { path = "../zkp-component", features = ["database-storage", "zkp-prover", "parallel"] }
nimiq-zkp-primitives = { path = "../zkp-primitives", features = ["parallel", "zkp-prover", "parallel"] }
