[package]
name = "nimiq-test-utils"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Test utilities for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[[bin]]
name = "nimiq-performance-history-store"
path = "src/performance/history-store/main.rs"

[[bin]]
name = "nimiq-performance-accounts-tree"
path = "src/performance/accounts-tree/main.rs"

[[bin]]
name = "nimiq-performance-blockchain-push"
path = "src/performance/blockchain-push/main.rs"

[dependencies]
ark-ff = "0.4"
ark-groth16 = { version = "0.4", default-features = false }
ark-mnt6-753 = "0.4"
ark-serialize = "0.4"
async-trait = "0.1"
clap = { version = "4.5", features = ["derive"] }
futures = { workspace = true }
hex = "0.4"
log = { workspace = true }
parking_lot = "0.12"
paste = "1.0"
rand = "0.8"
rand_chacha = "0.3.1"
serde = "1.0"
tempfile = "3.13"
tokio = { version = "1.41", features = ["rt", "time", "tracing"] }
tokio-stream = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

nimiq-account = { workspace = true }
nimiq-block = { workspace = true }
nimiq-blockchain = { workspace = true }
nimiq-blockchain-interface = { workspace = true }
nimiq-blockchain-proxy = { workspace = true }
nimiq-bls = { workspace = true }
nimiq-collections = { workspace = true }
nimiq-consensus = { workspace = true, features = ["full"] }
nimiq-database = { workspace = true }
nimiq-genesis = { workspace = true }
nimiq-genesis-builder = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-log = { workspace = true }
nimiq-mempool = { workspace = true }
nimiq-network-interface = { workspace = true }
nimiq-network-libp2p = { workspace = true }
nimiq-network-mock = { workspace = true }
nimiq-primitives = { workspace = true, features = ["tendermint"] }
nimiq-serde = { workspace = true }
nimiq-tendermint = { workspace = true }
nimiq-transaction = { workspace = true }
nimiq-transaction-builder = { workspace = true }
nimiq-trie = { workspace = true }
nimiq-utils = { workspace = true }
nimiq-validator = { workspace = true }
nimiq-validator-network = { workspace = true }
nimiq-vrf = { workspace = true }
nimiq-zkp-circuits = { workspace = true, features = ["test-setup", "zkp-prover", "parallel"] }
nimiq-zkp-component = { workspace = true, features = ["database-storage", "zkp-prover", "parallel"] }
nimiq-zkp-primitives = { workspace = true, features = ["parallel", "zkp-prover", "parallel"] }
