[package]
name = "nimiq-network"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq's network implementation in Rust"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
async-trait = "0.1"
atomic = "0.4"
futures = "0.1"
futures-03 = { package = "futures", version = "0.3" }
hex = "0.4"
log = "0.4"
native-tls = "0.2"
parking_lot = "0.11"
rand = "0.7"
reqwest = "0.9"
thiserror = "1.0"
tk-listen = "0.2.1"
tokio = "0.1"
tokio-02 = { package = "tokio", version = "1.9", features = ["sync"] }
tokio-stream = "0.1"
tokio-tls = "0.2"
tokio-tungstenite = "0.8"
url = "1.7"

beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive" }
nimiq-blockchain = { path = "../blockchain" }
nimiq-collections = { path = "../collections" }
nimiq-genesis = { path = "../genesis" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-messages = { path = "../messages" }
nimiq-macros = { path = "../macros" }
nimiq-network-interface = { path = "../network-interface" }
nimiq-peer-address = { path = "../peer-address" }
nimiq-utils = { path = "../utils", features = ["timers", "key-store", "observer", "mutable-once", "time", "unique-ptr", "iterators", "locking", "rate-limit", "unique-id"] }

[dependencies.tungstenite]
version = "0.8"
default-features = false

[features]
metrics = []
