[package]
name = "nimiq-network"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq's network implementation in Rust"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
atomic = "0.4"
failure = "0.1"
futures = "0.1"
hex = "0.3"
log = "0.4"
native-tls = "0.2"
parking_lot = "0.9"
rand = "0.6"
reqwest = "0.9"
tokio = "0.1"
tokio-tls = "0.2"
tokio-tungstenite = "0.8"
tk-listen = "0.2.1"
url = "1.7"
beserial = "0.1"
beserial_derive = "0.1"
nimiq-blockchain-base = "0.1"
nimiq-collections = "0.1"
nimiq-keys = "0.1"
nimiq-hash = "0.1"
nimiq-macros = "0.1"
nimiq-messages = "0.1"
nimiq-network-primitives = { version = "0.1", features = ["all"] }
nimiq-utils = { version = "0.1", features = ["timers", "key-store", "observer", "mutable-once", "time", "unique-ptr", "iterators", "locking", "rate-limit", "unique-id"] }

[dependencies.tungstenite]
version = "0.8"
default-features = false

[features]
metrics = []
