[package]
name = "nimiq-nano-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2021"

[[bin]]
name = "nimiq-pedersen-generators"

[dependencies]
num-traits = "0.2"
rayon = "^1.5"
hex = "0.4"

ark-crypto-primitives = "0.3"
ark-ec = "0.3"
ark-ff = "0.3"
ark-groth16 = "0.3"
ark-mnt4-753 = "0.3"
ark-mnt6-753 = "0.3"
ark-serialize = "0.3"

nimiq-bls = { path = "../bls" }
nimiq-hash = { path = "../hash" }
nimiq-primitives = { path = "../primitives", features = ["policy"] }

[dev-dependencies]
rand = "0.8"

nimiq-block = { path = "../primitives/block" }
nimiq-collections = { path = "../collections" }
nimiq-keys = { path = "../keys" }
nimiq-test-log = { path = "../test-log" }
nimiq-utils = { path = "../utils" }
nimiq-primitives = { path = "../primitives", features = ["slots"] }
