[package]
name = "nimiq-nano-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2021"

[dependencies]
num-traits = "0.2"
rayon = "^1.5"

ark-crypto-primitives = "0.3"
ark-ec = "0.3"
ark-groth16 = "0.3"
ark-mnt4-753 = "0.3"
ark-mnt6-753 = "0.3"

nimiq-bls = { path = "../bls", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-primitives = { path = "../primitives", features = ["policy"] }
