name = "dev-albatross"
seed_message = "Albatross DevNet"
signing_key = """9c4a1b36bf0a0a97b9d96713ee8cce211d321cdb368e06e53355c34a9733463f5b1897200f6af83fd3ea54f15bcbd9a5da772c\
79b0b06bd41fb95e06ebc4ba4174abe405c8339ac7540789b553d9454646649705cc5097e6643cbb0c0fb50000"""
# public_key = "008b308b8bd9e4e5865465fd6dd617c36d83f895464b4a75345ecbb9f1684a224ce43d3de9d5f8f4d2df404c4af0da4a42a07b0f
# ae0d377650b9a1c9338fbed055906028bf43bb9600634869af0aeb3b8ecf1298a183752e4da4889c6cd4d800065e98b4e51ea4e7cc5a8044900550
# 2a2e36be45c3d52684358acf39cd0dbbf88a3d9d0d2a632bd9745485e0b38e7118d8a88dd5bb4bdedbca01ab3cd728c8fc03fbe773ebd67a40bc06
# 407446157eefdf017749f1c58e47ca588ec96cf8001b3038b8f1d10acc0685f6c9c2cd1a5fa4a36db991a2d92230f1a407c1422c139fb52f1dcb66
# 1c1664e604e035ffd8ca1aca061f3374800805b6b654376fa08c9661fcff90be45282c0b962b4fddf92632fddc64c80dcc4bbab657e257dc"
timestamp="2019-05-10T23:56:52.776772644+00:00"
staking_contract = "NQ38 STAK 1NG0 0000 0000 C0NT RACT 0000 0000"

[[validators]]
reward_address = "NQ35 RRGL AKY0 1RAD R7M8 RM02 4MAD NF95 J0J4"
balance = 1000000000
validator_key = """01535b85d472b233642cce4f5ffd3b32e3dbd518a0124614a91cc6628d0d77a7e9d955125548c56b6c7812daa41519aaf8a2\
d9dbfb84f4b30ac6d18ee2619a015a1097fa25bd885bbc31ae4fb961884e4cf941cecdd25a70e6a0a726ba4b2d01696d325876808c592716569672d\
403fb41f19bc50e18e3df855bf6f053484de4be63658875dff127681681c9574d1d0c5d048053ec1b291234145f46167de7628bbaf971d8d89e8c6c\
29b5e2bc47cbd3be65331194822096b4cf092f644e004b7a2fc2cbeebc88d375095e2913127ca2de9eae486fbb0a8a671ff517a81169066ea1dca6e\
6745498f9ad5586b4c74ba5de7cbbe39ed4ec10714ca253d5f4fcc379f0a06a762b83e676bec4e6835899d6e639f4c90a00f1d3852f239b71"""
# secret_key = "f8ac8d3d52f72f86a97e83f6ccab9c8f60c70e92e13ea490ea3433b7611ab0058f0584d3e4a2b9856e482440967af01a6c878cb5
# ff0ea98acb07eec5fd0f5deb1db5fb2843d7bf34d7b9fddba5234943e6c3e491cbe08d071668affdf5d10000"

[[validators]]
reward_address = "NQ16 1KMX EFJ7 7BMV 2JPM 96RL H4K9 2653 28CY"
balance = 1000000000
validator_key = """000b17927b6293cd141488086073077392386c752c8d990340313ff7730e24497938a088c3694c827501e6474b3c288a075f\
919cc5eebde20a812cf2b475da77dc961eedcc0216bf53010e2df22dd19a20fe62f0416323a966a0b78ceb465d009700ed01a91f339a087580c86bf\
6b68e1c71d7bbebd65c5b5fca0b36c6f9bfcbb03cb4746d2164738dcbc9f825ac2edb6178a2b43665e615ad38fe9516ae671cc5c31eab5102c92a11\
1ca309d3a9fc88f64a0b56959db881d663bc085fc400668e719eb7a8ef674add0520f16f28b31864953c7899fb458d491486aea8e6d30ddb107e522\
e9409531e7d5aa877e6ef9a80ce88c176f6abc690daed3e07af5a88700bebb6c3833a198f13121f2ebf426560cbe933857f0ee522c8e430ec"""
# secret_key = "bfbf1e23855190f03222bb2b19dc9d25843494d22bf8ccc1f7abfe6b3b185b3bf76537ee70e7ac5c7c6d7a0046e671bf610572e1
# cf89b407a7cd095ab9f0868da80003121a26d4d3be1e1abd10861f6c8601e94e0e448f4b86b7512764460100"

[[stakes]]
staker_address = "NQ35 RRGL AKY0 1RAD R7M8 RM02 4MAD NF95 J0J4"
balance = 10000000
validator_key = """01535b85d472b233642cce4f5ffd3b32e3dbd518a0124614a91cc6628d0d77a7e9d955125548c56b6c7812daa41519aaf8a2\
d9dbfb84f4b30ac6d18ee2619a015a1097fa25bd885bbc31ae4fb961884e4cf941cecdd25a70e6a0a726ba4b2d01696d325876808c592716569672d\
403fb41f19bc50e18e3df855bf6f053484de4be63658875dff127681681c9574d1d0c5d048053ec1b291234145f46167de7628bbaf971d8d89e8c6c\
29b5e2bc47cbd3be65331194822096b4cf092f644e004b7a2fc2cbeebc88d375095e2913127ca2de9eae486fbb0a8a671ff517a81169066ea1dca6e\
6745498f9ad5586b4c74ba5de7cbbe39ed4ec10714ca253d5f4fcc379f0a06a762b83e676bec4e6835899d6e639f4c90a00f1d3852f239b71"""

[[stakes]]
staker_address = "NQ16 1KMX EFJ7 7BMV 2JPM 96RL H4K9 2653 28CY"
balance = 10000000
validator_key = """000b17927b6293cd141488086073077392386c752c8d990340313ff7730e24497938a088c3694c827501e6474b3c288a075f\
919cc5eebde20a812cf2b475da77dc961eedcc0216bf53010e2df22dd19a20fe62f0416323a966a0b78ceb465d009700ed01a91f339a087580c86bf\
6b68e1c71d7bbebd65c5b5fca0b36c6f9bfcbb03cb4746d2164738dcbc9f825ac2edb6178a2b43665e615ad38fe9516ae671cc5c31eab5102c92a11\
1ca309d3a9fc88f64a0b56959db881d663bc085fc400668e719eb7a8ef674add0520f16f28b31864953c7899fb458d491486aea8e6d30ddb107e522\
e9409531e7d5aa877e6ef9a80ce88c176f6abc690daed3e07af5a88700bebb6c3833a198f13121f2ebf426560cbe933857f0ee522c8e430ec"""

[[accounts]]
address = "NQ69 MU19 XRVJ 2P5G NTDL JF3K C24G LUCQ L43E"
balance = 10000000000000

[[accounts]]
address = "NQ84 LFLT Y6YA NBHJ P6PE BU52 UGXJ 8VFP 4DXY"
balance = 1000000000000

[[accounts]]
address = "NQ15 FV3Q 2QEN DSDG 9V7N NK0M P06R 4LTS D83T"
balance = 1000000000000

[[accounts]]
address = "NQ69 UMYS AUH5 UL42 SYFG 55KD S3XP 2PVF YQ6C"
balance = 1000000000000

[[accounts]]
address = "NQ09 A021 3L1J RTST PLKQ 89EQ BK69 SAK7 UEU1"
balance = 1000000000000

[[accounts]]
address = "NQ37 26PX KKXD 7VET F04P CD50 XPG7 RXQ6 9NUH"
balance = 1000000000000

[[accounts]]
address = "NQ51 N99J F4F0 KHAT TT22 LFHE 7UEX G8H3 GV1N"
balance = 1000000000000
