name = "dev-albatross"
seed_message = "Albatross DevNet"
timestamp = "2023-03-07T00:00:00.000+00:00"
vrf_seed = "e8c7f2f3935da9ca39419aa7d2cc90817245f75e58cc543f2b9478766308e8a50fffccb09e2df3546f5a0c0059d73a506c48fa2b546f15b511d0f7a63f0ee20cd510a87f520e26478bb687ca31a08db8b02921f9a22e32a790c07f16dbdf4501"

[[validators]]
validator_address = "NQ70 JM4N PU3R Y2U2 9RGX ABJE VKA4 4TBB HKF1"
signing_key = "81def5effc93ae283b5acfa466d0a544218b1bf3c3558f6cf6403bd9aed14dee"
voting_key = "8027fd05e6126d3e9ee10abfa10ad7eb05dfef5ce7e6ed338edf7cedd8988f61f259460a6e49e87470bb9c8caf6c5f79b0e1da7407838a2b59c292a7b82828d9d42c611fed323acc73697c97c605e686ed866ab81ea56d989b335028d3f06001bf231a1964a2830afa5eb22c4cc1677824aa947bea461941c55b5114b634122cb496386510c8a991147769233b223dc288ab62654c5de566be37402f705ee7c94663ef912a377c25899cdf17c56f82f23864f52cdae12bc83487cff154d700fb0db1c83c8fa37bf86f61c22265b46fa687fe8de3fc25fbecd5bfb283d2e902c3d535a994db79754ad234edcc32c0e8a65f28cda87dc1011cd9e9051abeec5ea2732b623137194861d7a0d344e87157a19f06f7da0857cdc26a1f186776"
reward_address = "NQ55 J6P2 9SLR 0GFQ XJKM P3MB HRJN NLFT EQ30"

[[validators]]
validator_address = "NQ83 P1EH GRM8 HUE8 GS7L CBST UVDS 778L HEX4"
signing_key = "418afdd60f6eb413de7e8048ed4e8cae8d0e4e3b2425f70986fe4779431e6120"
voting_key = "000e40ef49b8c60325542ce400bafdfeeb5c145a46b267f25693b6ae15515ef7da3534ca258984e4cc09b4bc16fb78f265f118362a664d00e7937a320949233309a50c188ea00f43c62066218dc6a3b64aa329ac0227967476491c8f14b8f401ab772faf58bd85a7be82a1ee013fa5de8af1542569b24e885e92a622313b37202b77ecb0a510b4bad1e940d2df939c01204c0c1fa59325da2e2c8dc2db85487aec55f5328e4e1aea01e95e28b872979951e26729ec401a4d6cfc91d10c20001fa0f675f907405c4689103e00ebd5cdb9293f00d70f6989e19f98579c8f3328585b3374c9ca8065753e9232e7ed3b38c2e953595205c6906caed7828180e78a018755702611ac2b611adb3bba0b140418bf7c040033da56391139ebe8a8"
reward_address = "NQ45 L3VX GNGA VDRF V6FL Q66Q Q884 S269 0MRT"

[[validators]]
validator_address = "NQ79 F94K NYV6 3V7D 68X6 FXAD 4PCM XMQR PP4U"
signing_key = "ee1424f128e4b8ae9a4951b7fb4717fa94cd9c74f29dbffdf591cdedbe149a8d"
voting_key = "8164b2092cc01bb37ee9af147d1d59ae9765c8a18effe00a993f6e7e6bc44fbc518c35f79df4884cb17db1d54e4ded1ca3ec6d15f3df5dc3e1de2f05cbaac222a95744b684aea1ce3164b22d4e65029c6ebdd1eac05a50aa423086560a959000d35806d08872ffd1ad4ad87ad3c605e5fb4077b3481b556694ee6440d096e0b94683229b6b9af7802f47b669340998a92beb492be8e3d4a9fbfe8af17d7bca79b95deeb5a2010d807a45ae4158da863d901df07c53d0f5b42836961640f8016d29727096694bab26215065e22e875e55a1d957a2a5176a2245100e086feedda74c74fc3ac85874b3d3f9f4e86e2030a3fd85f585b8a406f031bcda7b6de677d8ecb4cfcf009cf80bcecdfa19e0ecfa59b19e382c134709e2e717a782a6"
reward_address = "NQ94 4U2Y 8D9C VJJ6 1L1M FMG8 HUYL 7R6J AQ6Q"

[[validators]]
validator_address = "NQ94 58R8 YDR5 05EX JTA4 37JU N1EK 6R3Q M9C5"
signing_key = "a6f79373908fc283a6283165d45bd7706d3673e2ae6c7908113cfc7140c0f726"
voting_key = "814725950d9dda367361f15499a432911c01b3fdbba933e354a0f9ac5b76acbc7cd874169d8407cf64d8336e7f17a89c9b904f9fbcb2f83e17e243a20d6af8af294a307f21e7222f3dd1b9195ae6f10130b1b3ed87020a52387002ca1161030169a4182c22e15b3a996417c1fdb597c7ee198dd2810648f23253956960fddd1a9972cbe15a3dff8e4f7b0e83228766e843e285932e7b68c447894530be5b2c7f606547aa250113c5ae5286a043da527ee6fcbfe3cd2c106d78e88322141c01bf39ff6769a1de893bfad44318ba9570291730766e86a8c7cdfb4e2ce4bf878602491d9f99761a44b2ac7085577032306cc6c718d952aa78eade53a5ed2e9c171cefaeb3b5b6269888e24101908eb0d7dbe55d2f93b3b73d53794cc6d670"
reward_address = "NQ88 XHD8 8ULG PF17 3Q7N 3SGN AAYE XGS9 GV1F"

[[validators]]
validator_address = "NQ56 BBC5 B9RR PRT9 6V21 TJJ7 PJQ0 N5KA ELAU"
signing_key = "51483c5db7a578c3d5016ce98e5aea8051b5a3938fb28aaefa8e45d4d1e826c1"
voting_key = "80afc7638a29e0fd9d9310de5f06370b09c6a13ae75fa40625a8d7a8c9af7c266410deeedd35e45297477b418bd5762aa0ef1c7263397c3d368deeb627e1e5c6abb13282b0e7649f8ba2bef60ee4c36abae6b4f65b07efbaeb4ed7a18494a90190d5f9bec56c238a1f2bd67e809342e19085d40076e77d3372333ba070ee0e6e0480ce3aeb51278bbbc1992b76563a875b6c37147359770b9ecca4af3096f153304135617de5e6816494bf5c50f3765fd3a784137da43c36a13a31731d92015556f10fe8950faff8618b36b5d7e5d18ece5882b408d9b00e67036a732265ad907d3c1780f7097e1380027a27ce10f390bf96d1f5923378f504fa1b369424a235791bba82afa771a9c8d7a8c518f21d50d1e3c07da97774d6adadb2040f"
reward_address = "NQ91 YJNG P54M J335 JRVQ QDLY 4CYJ X5K9 R8RT"

[[validators]]
validator_address = "NQ69 GF5T BFJG 9YEX 97VJ JJ27 D9VA 414K 7LG5"
signing_key = "7cede71d0c20bcc3014635c79b4ca0d33759a3340f5799cba9368eb9ddc58df7"
voting_key = "018a3bbb657f200f866d0530457889c0c85051a460eaadf259fae630bbfec0fa348ef83116b56e937d65ced522d29e9c124f555df913b134c0a6d0712fd052e8c715dd6f483f661ed9ece738fb171318415a767b89f270e77bd98f1248e12d00b371a4c01833dddb2b6dc0b9bd4d3c904b8d358d2043a1ecedbfe5d37aa34c880c2c923e12b635f4f98250f90e42c5202c83c9fbcd4d025bbc6886f0db95939e1a2705315868897bde91354c9685c277b0b2a97f0a889634c10b79592a0800bf8f5b0e2060db579a9938e1fa62d0774ecf2e16db02c4cf07dc91b2598adf046dfa294ac98c5aa8a730d50fd0f385fc457dfd321ed6305b1b7b83cdab0ea0f83a38047862d9943a0128adf1bfb25bf12cc4b31d32e1d21bb3917c8fdb76"
reward_address = "NQ62 JE6M Q130 MF10 M92K HQRR P394 L8MK HE7R"

[[validators]]
validator_address = "NQ85 UD3C U8F9 J1L9 J32V X9QX S3NJ BQ4L SCAN"
signing_key = "9c630945f2764818e8ea0924b8cea68a6680aa344edfd8103fd882392556ca03"
voting_key = "81a621896784df6af8e1e8e9751642d7d8be828ff2c982598271c0e13ee77c9c7074ac8491d5a1cce40b65bed590d8fc3764b194939d05b7319329d119dc8fa5e268b23d11f756438dd712fa6bc2383b9fcc235e5787e786fc495b205d3e3b013363a9ee489aaa2335136dbf1db96127d975d71fc10e779c82b6013d0c8982eef859547d6fb8c0026a9871608bfc1bdae41ab42f9133ac69e56621fc91f552df897ed6b22acdf1cb4f150e661c4148938e6b724e025cc69d77ab7e3cdc400117ea69beb469a5ceb43efcfcee31f6c24eae0966c1d3e96c6a63244b9e1529aa86fc551a24990e6f74da03268c7f9dc59e3328434a9e2b7b1b696baada6caea0919c02074f5414be8155deb87319010f5dc03ba6b0f17fa0a984599ca492"
reward_address = "NQ19 7SNT KSMT 0P1N M16R QJEB EYSJ M5BQ R673"

[[validators]]
validator_address = "NQ84 3NMP N7X3 90XQ G8PB 48V3 M15Y B9V0 6C41"
signing_key = "d419c718543cbeb6068e322800d53aeb7bc90f221fcc92c80247ccd914ced438"
voting_key = "805692d88e36a572dacedbf0f002908c617a2bc8e7cbbabb92a8f2864084a361b1f4887c88e975e565e3119ff630c11fa81e5ae49a57d5edc0e39828f1ab75495ebf20afd809cf00c0f902ea0046e8c08151f8e76f2e3a6041bcc261c577ec0102eeaeaf53ec78c531b8162663258e6f352de9aea2bc5f80dec9c0cbeb22da8aca30c63af19b157224bca3418b0d7a84ca85117bd9338ad9594b862d9081dec44528769651041c26229d4807efb4277fb165b390da2d8fe5e52b7401f64001b37e85e4490dc56de323c9559e8982b5d88ff887170e05ce67e35c1a03843109006c1e3371ceabe8caf3b13e37392a41d44b032047908c6cfa581b941d6831cd80a12c599aea8fa35849437caf693cbb0d7a0228c06d11f4a57eae5f3791"
reward_address = "NQ53 LC70 JHGH UEMV 2CAB DFQL JKHQ 21FS D3AY"

[[stakers]]
staker_address = "NQ55 J6P2 9SLR 0GFQ XJKM P3MB HRJN NLFT EQ30"
balance = 1_000_000
delegation = "NQ70 JM4N PU3R Y2U2 9RGX ABJE VKA4 4TBB HKF1"

[[stakers]]
staker_address = "NQ45 L3VX GNGA VDRF V6FL Q66Q Q884 S269 0MRT"
balance = 1_000_000
delegation = "NQ83 P1EH GRM8 HUE8 GS7L CBST UVDS 778L HEX4"

[[stakers]]
staker_address = "NQ94 4U2Y 8D9C VJJ6 1L1M FMG8 HUYL 7R6J AQ6Q"
balance = 1_000_000
delegation = "NQ79 F94K NYV6 3V7D 68X6 FXAD 4PCM XMQR PP4U"

[[stakers]]
staker_address = "NQ88 XHD8 8ULG PF17 3Q7N 3SGN AAYE XGS9 GV1F"
balance = 1_000_000
delegation = "NQ94 58R8 YDR5 05EX JTA4 37JU N1EK 6R3Q M9C5"

[[stakers]]
staker_address = "NQ91 YJNG P54M J335 JRVQ QDLY 4CYJ X5K9 R8RT"
balance = 1_000_000
delegation = "NQ56 BBC5 B9RR PRT9 6V21 TJJ7 PJQ0 N5KA ELAU"

[[stakers]]
staker_address = "NQ62 JE6M Q130 MF10 M92K HQRR P394 L8MK HE7R"
balance = 1_000_000
delegation = "NQ69 GF5T BFJG 9YEX 97VJ JJ27 D9VA 414K 7LG5"

[[stakers]]
staker_address = "NQ19 7SNT KSMT 0P1N M16R QJEB EYSJ M5BQ R673"
balance = 1_000_000
delegation = "NQ85 UD3C U8F9 J1L9 J32V X9QX S3NJ BQ4L SCAN"

[[stakers]]
staker_address = "NQ53 LC70 JHGH UEMV 2CAB DFQL JKHQ 21FS D3AY"
balance = 1_000_000
delegation = "NQ84 3NMP N7X3 90XQ G8PB 48V3 M15Y B9V0 6C41"

[[accounts]]
address = "NQ37 7C3V VMN8 FRPN FXS9 PLAG JMRE 8SC6 KUSQ"
balance = 250_000_000_00000

[[accounts]]
address = "NQ21 CHG8 N0CF 8P8U R037 C6K4 AMS7 HET4 QM90"
balance = 750_000_000_00000
