name = "dev-albatross"
seed_message = "Albatross DevNet"
signing_key = """9c4a1b36bf0a0a97b9d96713ee8cce211d321cdb368e06e53355c34a9733463f5b1897200f6af83fd3ea54f15bcbd9a5da772c\
79b0b06bd41fb95e06ebc4ba4174abe405c8339ac7540789b553d9454646649705cc5097e6643cbb0c0fb50000"""
# public_key = "008b308b8bd9e4e5865465fd6dd617c36d83f895464b4a75345ecbb9f1684a224ce43d3de9d5f8f4d2df404c4af0da4a42a07b0f
# ae0d377650b9a1c9338fbed055906028bf43bb9600634869af0aeb3b8ecf1298a183752e4da4889c6cd4d800065e98b4e51ea4e7cc5a8044900550
# 2a2e36be45c3d52684358acf39cd0dbbf88a3d9d0d2a632bd9745485e0b38e7118d8a88dd5bb4bdedbca01ab3cd728c8fc03fbe773ebd67a40bc06
# 407446157eefdf017749f1c58e47ca588ec96cf8001b3038b8f1d10acc0685f6c9c2cd1a5fa4a36db991a2d92230f1a407c1422c139fb52f1dcb66
# 1c1664e604e035ffd8ca1aca061f3374800805b6b654376fa08c9661fcff90be45282c0b962b4fddf92632fddc64c80dcc4bbab657e257dc"
timestamp="2019-05-10T23:56:52.776772644+00:00"
staking_contract = "NQ38 STAK 1NG0 0000 0000 C0NT RACT 0000 0000"

[[validators]]
validator_id = "0000000000000000000000000000000000000000"
reward_address = "NQ35 RRGL AKY0 1RAD R7M8 RM02 4MAD NF95 J0J4"
balance = 1000000000
validator_key = """01535b85d472b233642cce4f5ffd3b32e3dbd518a0124614a91cc6628d0d77a7e9d955125548c56b6c7812daa41519aaf8a2\
d9dbfb84f4b30ac6d18ee2619a015a1097fa25bd885bbc31ae4fb961884e4cf941cecdd25a70e6a0a726ba4b2d01696d325876808c592716569672d\
403fb41f19bc50e18e3df855bf6f053484de4be63658875dff127681681c9574d1d0c5d048053ec1b291234145f46167de7628bbaf971d8d89e8c6c\
29b5e2bc47cbd3be65331194822096b4cf092f644e004b7a2fc2cbeebc88d375095e2913127ca2de9eae486fbb0a8a671ff517a81169066ea1dca6e\
6745498f9ad5586b4c74ba5de7cbbe39ed4ec10714ca253d5f4fcc379f0a06a762b83e676bec4e6835899d6e639f4c90a00f1d3852f239b71"""
# secret_key = "f8ac8d3d52f72f86a97e83f6ccab9c8f60c70e92e13ea490ea3433b7611ab0058f0584d3e4a2b9856e482440967af01a6c878cb5
# ff0ea98acb07eec5fd0f5deb1db5fb2843d7bf34d7b9fddba5234943e6c3e491cbe08d071668affdf5d10000"

[[validators]]
validator_id = "1111111111111111111111111111111111111111"
reward_address = "NQ16 1KMX EFJ7 7BMV 2JPM 96RL H4K9 2653 28CY"
balance = 1000000000
validator_key = """000b17927b6293cd141488086073077392386c752c8d990340313ff7730e24497938a088c3694c827501e6474b3c288a075f\
919cc5eebde20a812cf2b475da77dc961eedcc0216bf53010e2df22dd19a20fe62f0416323a966a0b78ceb465d009700ed01a91f339a087580c86bf\
6b68e1c71d7bbebd65c5b5fca0b36c6f9bfcbb03cb4746d2164738dcbc9f825ac2edb6178a2b43665e615ad38fe9516ae671cc5c31eab5102c92a11\
1ca309d3a9fc88f64a0b56959db881d663bc085fc400668e719eb7a8ef674add0520f16f28b31864953c7899fb458d491486aea8e6d30ddb107e522\
e9409531e7d5aa877e6ef9a80ce88c176f6abc690daed3e07af5a88700bebb6c3833a198f13121f2ebf426560cbe933857f0ee522c8e430ec"""
# secret_key = "bfbf1e23855190f03222bb2b19dc9d25843494d22bf8ccc1f7abfe6b3b185b3bf76537ee70e7ac5c7c6d7a0046e671bf610572e1
# cf89b407a7cd095ab9f0868da80003121a26d4d3be1e1abd10861f6c8601e94e0e448f4b86b7512764460100"

[[validators]]
validator_id = "1111111111111111111111111111111111111112"
reward_address = "NQ35 RRGL AKY0 1RAD R7M8 RM02 4MAD NF95 J0J4"
balance = 1000000000
validator_key = """00b21b3876bd48bea9411af5915914f9b6ef1bf2c7bfdf3e9f7f9db639598c70093a7046ca1c39340d827e850f8e96bd5209\
48954262f1e8779c664a0254961690fc330feb8bcd2436e5583cac2fde5c2f3bdc45daea29cfb21a5f540069fe00df72a05514cd98f653ac666373d\
bbccb06374b1b7c5785c771b9881e288883e35df0fd8374934aa043441b982d38a073623b86261ecbc04a05670436674ff19ec53572ca37f30fbfa3\
d94bc7cfec5eb1efcc5b384f3acbe8a8b65a9c2b3000a5f746a08277194ee0e13b0b5540f26bf842dd0b267fb3e45a943b82b3e2f25a2670936cb98\
fbcbe95940a134f0abf4e63bebcbfa0c580b5c4f3c3473c8c66dab0c09efdb916dd112db9e399b000c732125d95cb05c693b9a20988d3d95b"""
# secret_key = "eacdbf28aff34ca60f0b57c98d5b4bb32948710d4afa4b3567d21ef871845ada28bc6721b7720ce74242d45674cbc91e317c64f1
# 109b547ef07d13f4e5e936ebd1e68a292f82c71dbb50f6ef68386b8066efa9e40aaa637f86922e90f73f0100"

[[validators]]
validator_id = "1111111111111111111111111111111111111113"
reward_address = "NQ35 RRGL AKY0 1RAD R7M8 RM02 4MAD NF95 J0J4"
balance = 1000000000
validator_key = """0132109cdb9c66181e2cc39695f55429b85802b576dd72af1799ca0b4a8d2d169d0a017745847629b05f7a289223d4b5f4d0\
89fdec8e1a4e7eab12d39749d79e7d4fbfc02f5da21b172dcdb71de933fc0607d51127d9674ff24a29c6201fdc012102dd45b2412ebbfbaa59cb986\
879513118d30f70893fb216c72b3a664a2c9c83d99f22768b50a86e755bdc4d6d9a3e7f5f55512a1cc55c020cb134f9a65fecf1fef6eafed28f359f\
af8c5e3427713c299c0921537dd98c67f33203ad610126de7c578ebfaa0f517ade8f51b9747db3ffce67df7b3f2c9f64d288d3786b72536ca893374\
7b4c719eed158239ccae4df53164f3745dee969bc67f116fc17a3b58d70dd0593118491ba8ba7dbcb994bfcf7b1cc62616565228cdbcb3ad6"""
# secret_key = "1aa577387bd1b63ee93dc2aa5547d6c3e78494ebffbbbecc6cdddf058d98c3be543b4454b6e3fe01a3c9d1e3ca35933d96727e29
# e47e48077488288b02bf8c0a3954ea20471723194a83099f9b434ad47fc67b3d44c61cca134ab9bc0df00000"

[[stakes]]
staker_address = "NQ35 RRGL AKY0 1RAD R7M8 RM02 4MAD NF95 J0J4"
balance = 10000000
validator_id = "0000000000000000000000000000000000000000"

[[stakes]]
staker_address = "NQ35 RRGL AKY0 1RAD R7M8 RM02 4MAD NF95 J0J4"
balance = 10000000
validator_id = "1111111111111111111111111111111111111112"

[[stakes]]
staker_address = "NQ35 RRGL AKY0 1RAD R7M8 RM02 4MAD NF95 J0J4"
balance = 10000000
validator_id = "1111111111111111111111111111111111111113"

[[stakes]]
staker_address = "NQ16 1KMX EFJ7 7BMV 2JPM 96RL H4K9 2653 28CY"
balance = 10000000
validator_id = "1111111111111111111111111111111111111111"

[[accounts]]
address = "NQ69 MU19 XRVJ 2P5G NTDL JF3K C24G LUCQ L43E"
balance = 10000000000000

[[accounts]]
address = "NQ84 LFLT Y6YA NBHJ P6PE BU52 UGXJ 8VFP 4DXY"
balance = 1000000000000

[[accounts]]
address = "NQ15 FV3Q 2QEN DSDG 9V7N NK0M P06R 4LTS D83T"
balance = 1000000000000

[[accounts]]
address = "NQ69 UMYS AUH5 UL42 SYFG 55KD S3XP 2PVF YQ6C"
balance = 1000000000000

[[accounts]]
address = "NQ09 A021 3L1J RTST PLKQ 89EQ BK69 SAK7 UEU1"
balance = 1000000000000

[[accounts]]
address = "NQ37 26PX KKXD 7VET F04P CD50 XPG7 RXQ6 9NUH"
balance = 1000000000000

[[accounts]]
address = "NQ51 N99J F4F0 KHAT TT22 LFHE 7UEX G8H3 GV1N"
balance = 1000000000000
