name = "unit-albatross"
seed_message = "Albatross Genesis for Unit Tests"
timestamp = "2021-10-30T02:04:20.999999999-06:00"
vrf_seed = "e8c7f2f3935da9ca39419aa7d2cc90817245f75e58cc543f2b9478766308e8a508633d7b5d08eea96770d55fe74c66660bff9f05f84c07f6b4760077ec0cab0a7b9b619db44f847f725d953d5856217b9b1caff25f4434b41c87cfe61f512904"

[[validators]]
validator_address = "NQ20 TSB0 DFSM UH9C 15GQ GAGJ TTE4 D3MA 859E"
# secret_key = 6927eb8de74e8ea06a8afae5a66db176a7031f742b656651ac53bddb8a4ad3f3
signing_key = "7a4d16d80d0afab4af8dc38e4ebd20cf46f5b8aa8cd5baa45a52717ae976119c"
# secret_key = 041580cc67e66e9e08b68fd9e4c9deb68737168fbe7488de2638c2e906c2f5ad
voting_key = """8137f759a2c836228f082b16cecd713467538b3e16fb8f61bd3bd0647c3c6d2d8a9ded144da6f2d07544cccac1222d771d61\
a8e7197a1dd3567723d26681f96333ed0d04820534c99e4c05064c8d61a5b4ee32153dbdd9efaf5041f5a78d8c000263d28beb873c092940ce87611\
b455e408a7d32fff9d2fb8e76c28914d48245fe172786e3d7a09e7b4c0e25cd902a9c684673c6d84f2d4fc9aad2fa3c74e8fbb66e0ce62406e34bad\
214155f2884f444acdcb4b4e67d01533f72a13e42800744da4d37f54295a0a49543227a78f242ca730c2b9b5e5cdefcef43d60f4ddaf7d0ccfc6ac8\
067c6f8cf2b4491709b43359cb05b90b31be46e4ebc36e43e30dcbf0eabef1542743eeb53f9bd01e5344b8284d16bc3d5ed72612bfa7fd922"""
# secret_key = "196ffdb1a8acc7cbd76a251aeac0600a1d68b3aba1eba823b5e4dc5dbdcdc730afa752c05ab4f6ef8518384ad514f403c5a088a
# 22b17bf1bc14f8ff8decc2a512c0a200f68d7bdf5a319b30356fe8d1d75ef510aed7a8660968c216c328a0000"
reward_address = "NQ46 U66M JNLD 0DJ7 0E9P Q7XR V9KV H976 813A"
# secret_key = 6c9320ac201caf1f8eaa5b05f5d67a9e77826f3f6be266a0ecccc20416dc6587

[[stakers]]
staker_address = "NQ39 VBTN P2HX Q3MF KHF1 CCLA G6FS 9B8S VY28"
# secret_key = 12004e8b2114b4ec0848154a0209928ddd3199ccb706e41c2e72295c7574ce0b
balance = 100_000
delegation = "NQ20 TSB0 DFSM UH9C 15GQ GAGJ TTE4 D3MA 859E"

[[accounts]]
address = "NQ46 U66M JNLD 0DJ7 0E9P Q7XR V9KV H976 813A"
# secret_key = 6c9320ac201caf1f8eaa5b05f5d67a9e77826f3f6be266a0ecccc20416dc6587
balance = 10_000_000_00000
