name = "unit-albatross"
seed_message = "Albatross Genesis for Unit Tests"
signing_key = "99e7fa3c24074386ff6331e2fc6812c9dc6699f7f95891b38ec48283c8a22835831ef6e35261f7374509f563424a4cd71d98caae7d4cc2568aa43f8d9421dcb6084662aa9e2dd10aadde79998a1a100a6068b40a220cd93e6b319259b6cc0000"
timestamp = "2019-08-18T02:04:20.999999999+02:00"

[[validators]]
validator_id = "0000000000000000000000000000000000000000"
reward_address = "NQ57 UC15 80L7 LHCK DBTB 709R M91Q PRG5 DL00"
balance = 100000
validator_key = "8137f759a2c836228f082b16cecd713467538b3e16fb8f61bd3bd0647c3c6d2d8a9ded144da6f2d07544cccac1222d771d61a8e7197a1dd3567723d26681f96333ed0d04820534c99e4c05064c8d61a5b4ee32153dbdd9efaf5041f5a78d8c000263d28beb873c092940ce87611b455e408a7d32fff9d2fb8e76c28914d48245fe172786e3d7a09e7b4c0e25cd902a9c684673c6d84f2d4fc9aad2fa3c74e8fbb66e0ce62406e34bad214155f2884f444acdcb4b4e67d01533f72a13e42800744da4d37f54295a0a49543227a78f242ca730c2b9b5e5cdefcef43d60f4ddaf7d0ccfc6ac8067c6f8cf2b4491709b43359cb05b90b31be46e4ebc36e43e30dcbf0eabef1542743eeb53f9bd01e5344b8284d16bc3d5ed72612bfa7fd922"
# secret_key = "196ffdb1a8acc7cbd76a251aeac0600a1d68b3aba1eba823b5e4dc5dbdcdc730afa752c05ab4f6ef8518384ad514f403c5a088a22b17bf1bc14f8ff8decc2a512c0a200f68d7bdf5a319b30356fe8d1d75ef510aed7a8660968c216c328a0000"

[[stakes]]
staker_address = "NQ57 UC15 80L7 LHCK DBTB 709R M91Q PRG5 DL00"
balance = 100000
validator_id = "0000000000000000000000000000000000000000"

[[accounts]]
address = "NQ57 UC15 80L7 LHCK DBTB 709R M91Q PRG5 DL00"
balance = 1000000
