[package]
name = "nimiq-messages"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Messages send over the nimiq network"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
bitflags = "1.0"
bitvec = "0.17"
byteorder = "1.2"
hex = "0.4"
log = "0.4"
parking_lot = "0.11"
rand = "0.7"
thiserror = "1.0"

beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive" }
nimiq-account = { path = "../primitives/account" }
nimiq-block = { path = "../primitives/block" }
nimiq-bls = { path = "../bls" }
nimiq-handel = { path = "../handel" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-macros = { path = "../macros" }
nimiq-network-interface = { path = "../network-interface" }
nimiq-peer-address = { path = "../peer-address" }
nimiq-subscription = { path = "../primitives/subscription" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-trie = { path = "../primitives/trie" }
nimiq-utils = { path = "../utils", features = ["observer", "crc"] }

[dev-dependencies]
nimiq-utils = { path = "../utils", features = ["observer", "crc", "time", "iterators"] }
