[package]
name = "nimiq-mnemonic"
version.workspace = true
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
license.workspace = true
edition.workspace = true
description = "Mnemonic helper library for Nimiq"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
bitvec = "1.0"
hex = "0.4"
serde = "1.0"
unicode-normalization = "0.1"

nimiq-hash = { workspace = true }
nimiq-key-derivation = { workspace = true, optional = true }
nimiq-macros = { workspace = true }
nimiq-utils = { workspace = true, features = ["crc"] }

[dev-dependencies]
nimiq-test-log = { workspace = true }

[features]
default = ["key-derivation"]
key-derivation = ["nimiq-key-derivation"]
