[package]
name = "nimiq-mnemonic"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Mnemonic helper library for Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
bit-vec = "0.5"
hex = "0.3"
unicode-normalization = "0.1"
nimiq-hash = { path = "../hash", version = "0.1" }
beserial = { path = "../beserial", version = "0.1" }
nimiq-macros = { path = "../macros", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["bit-vec", "crc"] }
nimiq-key-derivation = { path = "../key-derivation", version = "0.1", optional = true }

[features]
default = ["key-derivation"]
key-derivation = ["nimiq-key-derivation"]