[package]
name = "nimiq-zkp-test-gen"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "All functionality related to the zk proof storage, dissemination and request handeling."
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
parking_lot = "0.12"
serde = "1.0"
tokio = { version = "1.37", features = ["macros", "rt", "sync"] }
tracing-subscriber = { version = "0.3" }

nimiq-block = { workspace = true }
nimiq-blockchain = { workspace = true }
nimiq-blockchain-interface = { workspace = true }
nimiq-blockchain-proxy = { workspace = true }
nimiq-database = { workspace = true }
nimiq-genesis = { workspace = true }
nimiq-log = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy"] }
nimiq-serde = { workspace = true }
nimiq-test-utils = { workspace = true }
nimiq-utils = { workspace = true, features = [
    "time",
] }
nimiq-zkp = { workspace = true, features = ["zkp-prover"] }
nimiq-zkp-circuits = { workspace = true, features = ["zkp-prover"] }
nimiq-zkp-component = { workspace = true, features = ["zkp-prover"] }
nimiq-zkp-primitives = { workspace = true, features = ["zkp-prover"] }
