[package]
name = "nimiq-test-log-proc-macro"
version.workspace = true
authors = ["Daniel Mueller <deso@posteo.net>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
include = ["src/lib.rs", "LICENSE-*", "README.md", "CHANGELOG.md"]

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
tokio = { version = "1.40", features = ["macros", "rt"] }

nimiq-test-log = { workspace = true }
