[package]
name = "nimiq-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
postcard = { version = "1.0", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde-big-array = "0.5"
