[package]
name = "nimiq-test-log"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq logging utilities for testing"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
log = { workspace = true }
parking_lot = "0.12"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

nimiq-genesis = { workspace = true }
nimiq-log = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy"] }
nimiq-test-log-proc-macro = { workspace = true }
