[package]
name = "nimiq-peer-address"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2021"
description = "Nimiq peer address"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
bitflags = "1.0"
thiserror = "1.0"
hex = "0.4"
lazy_static = "1.2"
url = "2.2"

beserial = { path = "../beserial", features = ["derive", "net"] }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-macros = { path = "../macros" }
nimiq-utils = { path = "../utils", features = ["observer", "time"] }

[dev-dependencies]
nimiq-test-log = { path = "../test-log" }

[build-dependencies]
nimiq-genesis-builder = { path = "../genesis-builder" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
