[package]
name = "nimiq-nano-zkp"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Recursive SNARKs for Nimiq's Nano Nodes"
license = "Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2021"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[dependencies]
thiserror = "1.0.31"
rand = { version = "0.8", features = ["small_rng"] }

ark-crypto-primitives = "0.3"
ark-ec = "0.3"
ark-ff = "0.3"
ark-groth16 = "0.3"
ark-mnt4-753 = "0.3"
ark-mnt6-753 = "0.3"
ark-relations = "0.3"
ark-r1cs-std = "0.3.1"
ark-serialize = "0.3"
ark-std = "0.3"
ark-sponge = { git = "https://github.com/arkworks-rs/sponge" }

nimiq-bls = { path = "../bls" }
nimiq-nano-primitives = { path = "../nano-primitives" }
nimiq-primitives = { path = "../primitives", features = ["policy"] }

[dev-dependencies]
nimiq-test-log = { path = "../test-log" }

[features]
prover = ["ark-crypto-primitives/r1cs", "ark-mnt4-753/r1cs", "ark-mnt6-753/r1cs", "ark-groth16/r1cs"]

[[example]]
name = "setup"
path = "examples/prover/setup.rs"
required-features = ["prover"]

[[example]]
name = "prove"
path = "examples/prover/prove.rs"
required-features = ["prover"]
