[package]
name = "nimiq-rpc-server"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "JSON RPC server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
base64 = "0.10"
beserial = { path = "../beserial", version = "0.1" }
clear_on_drop = "0.2"
failure = "0.1"
futures = "0.3"
hex = "0.4"
hyper = "0.13"
json = "0.12"
log = "0.4"
parking_lot = "0.9"

nimiq-account = { path = "../primitives/account", version = "0.1" }
nimiq-block = { path = "../primitives/block", version = "0.1" }
nimiq-block-albatross = { path = "../primitives/block-albatross", version = "0.1" }
nimiq-block-base = { path = "../primitives/block-base", version = "0.1" }
nimiq-block-production = { path = "../block-production", version = "0.1" }
nimiq-blockchain = { path = "../blockchain", version = "0.1", features = ["metrics"] }
nimiq-blockchain-albatross = { path = "../blockchain-albatross", version = "0.1", features = ["metrics"] }
nimiq-blockchain-base = { path = "../blockchain-base", version = "0.1" }
nimiq-bls = { path = "../bls", version = "0.1" }
nimiq-consensus = { path = "../consensus", version = "0.1" }
nimiq-database = { path = "../database", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-keys = { path = "../keys", version = "0.1" }
nimiq-mempool = { path = "../mempool", version = "0.1" }
nimiq-network = { path = "../network", version = "0.1", features = ["metrics"] }
nimiq-network-primitives = { path = "../network-primitives", version = "0.1" }
nimiq-primitives = { path = "../primitives", version = "0.1" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["merkle", "time", "otp"] }
nimiq-validator = { path = "../validator", version = "0.1", optional = true}
nimiq-wallet = { path = "../wallet", version = "0.1" }

[features]
validator = ["nimiq-validator"]