[package]
name = "nimiq-rpc-server"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "JSON RPC server for the Nimiq Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
futures = { workspace = true }
hex = "0.4.2"
log = { workspace = true }
parking_lot = "0.12"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = "1.40"
tokio-stream = "0.1"

nimiq-account = { workspace = true }
nimiq-block = { workspace = true }
nimiq-blockchain = { workspace = true }
nimiq-blockchain-interface = { workspace = true }
nimiq-blockchain-proxy = { workspace = true, features = ["full"] }
nimiq-bls = { workspace = true, features = ["serde-derive"] }
nimiq-collections = { workspace = true }
nimiq-consensus = { workspace = true, features = ["full"] }
nimiq-database = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-jsonrpc-core = { workspace = true }
nimiq-jsonrpc-derive = { workspace = true }
nimiq-jsonrpc-server = { workspace = true }
nimiq-keys = { workspace = true, features = ["serde-derive"] }
nimiq-mempool = { workspace = true }
nimiq-network-interface = { workspace = true }
nimiq-network-libp2p = { workspace = true }
nimiq-primitives = { workspace = true, features = [
    "coin",
    "account",
    "serde-derive",
] }
nimiq-rpc-interface = { workspace = true }
nimiq-serde = { workspace = true }
nimiq-transaction = { workspace = true }
nimiq-transaction-builder = { workspace = true, features = [
    "serde-derive",
] }
nimiq-utils = { workspace = true, features = ["otp"] }
nimiq-validator = { workspace = true }
nimiq-validator-network = { workspace = true }
nimiq-vrf = { workspace = true, features = ["serde-derive"] }
nimiq-wallet = { workspace = true, features = ["store"] }
nimiq-zkp-component = { workspace = true }
