[package]
name = "nimiq-rpc-server"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "JSON RPC server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
async-trait = "0.1"
futures = "0.3"
hex = "0.4.2"
log = "0.4"
parking_lot = { git = "https://github.com/styppo/parking_lot.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.4"
thiserror = "1.0"
tokio = "1.14"
tokio-stream = "0.1"

beserial = { path = "../beserial" }
nimiq-account = { path = "../primitives/account", features = ["serde-derive"] }
nimiq-block = { path = "../primitives/block", features = ["serde-derive"] }
nimiq-blockchain = { path = "../blockchain" }
nimiq-bls = { path = "../bls", features = ["serde-derive"] }
nimiq-collections = { path = "../collections", features = [
    "serde-derive",
    "bitset",
] }
nimiq-consensus = { path = "../consensus" }
nimiq-database = { path = "../database" }
nimiq-hash = { path = "../hash", features = ["serde-derive"] }
nimiq-jsonrpc-core = { git = "https://github.com/nimiq/jsonrpc.git" }
nimiq-jsonrpc-derive = { git = "https://github.com/nimiq/jsonrpc.git" }
nimiq-jsonrpc-server = { git = "https://github.com/nimiq/jsonrpc.git" }
nimiq-keys = { path = "../keys", features = ["serde-derive"] }
nimiq-mempool = { path = "../mempool" }
nimiq-network-interface = { path = "../network-interface" }
nimiq-network-libp2p = { path = "../network-libp2p" }
nimiq-primitives = { path = "../primitives", features = [
    "coin",
    "account",
    "serde-derive",
] }
nimiq-rpc-interface = { path = "../rpc-interface", features = ["proxy"] }
nimiq-transaction = { path = "../primitives/transaction", features = [
    "serde-derive",
] }
nimiq-transaction-builder = { path = "../transaction-builder", features = [
    "serde-derive",
] }
nimiq-utils = { path = "../utils", features = ["otp"] }
nimiq-validator = { path = "../validator" }
nimiq-validator-network = { path = "../validator-network" }
nimiq-vrf = { path = "../vrf", features = ["serde-derive"] }
nimiq-wallet = { path = "../wallet" }
