name: Build + Release docker

on:
  push:
    tags:
      - 'v*'

jobs:
  rust_build:
    name: Build Nimiq with release flag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nimiq-dist
          path: |
            target/release/nimiq-client
            target/release/nimiq-bls
            target/release/nimiq-address
            target/release/nimiq-rpc

  build_docker:
    runs-on: ubuntu-22.04
    name: Build & publish docker image
    needs: rust_build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download nimiq client artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: nimiq-dist
          path: target/release/

      - name: Run some commands
        run: |
          rm .dockerignore
          ls target/release/ -al
          chmod -R +x target/release/
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=true

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: Dockerfile.prod
          push: ${{ github.ref_type == 'tag' }}
          # This is required or a package with unknown architecture will be published too.
          # See https://github.com/docker/build-push-action/issues/820 for further
          # details.
          # TODO - investigate further and see if we can find a solution where we
          # don't have to set this.
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
