name: Release Mode Scenarios

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
    default: "default"

jobs:

  FiveValidatorsWithSpammer:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          sh
    - uses: actions/cache@v2
      with:
        path:
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Executes the test
      run: |
          bash scripts/devnet/devnet.sh --validators 5 -R -s 500 -k 0
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: FiveValidatorsWithSpammer-logs
          path: |
            temp-logs/
    - name: Retrieve failure reason
      if: always()
      run: |
          if [ -f temp-state/RESULT.TXT ]; then
            echo "::set-output name=FAIL_REASON::$(cat temp-state/RESULT.TXT)"
          else
            echo "::set-output name=FAIL_REASON::other"
          fi
      id: reason
    - name: Report potential deadlocks to slack
      if: always() && contains(steps.reason.outputs.FAIL_REASON, 'DEADLOCK')
      uses: ravsamhq/notify-slack-action@v1
      with:
          status: ${{ job.status }}
          notification_title: 'Potential deadlock detected in FiveValidatorsWithSpammer'
          footer: '<{run_url}|View Run>'
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
    - name: Report long lock hold times
      if: always() && contains(steps.reason.outputs.FAIL_REASON, 'LONG_LOCK_HOLD_TIME')
      uses: ravsamhq/notify-slack-action@v1
      with:
          status: ${{ job.status }}
          notification_title: 'Long lock hold time detected in FiveValidatorsWithSpammer'
          footer: '<{run_url}|View Run>'
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
    - name: Report slow lock acquisitions
      if: always() && contains(steps.reason.outputs.FAIL_REASON, 'SLOW_LOCK_ACQUISITION')
      uses: ravsamhq/notify-slack-action@v1
      with:
          status: ${{ job.status }}
          notification_title: 'Slow lock acquisition detected in FiveValidatorsWithSpammer'
          footer: '<{run_url}|View Run>'
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
    - name: Report Status to Slack
      if: always() && github.ref == 'refs/heads/albatross'
      uses: ravsamhq/notify-slack-action@v1
      with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'FiveValidatorsWithSpammer failed because of ${{ steps.reason.outputs.FAIL_REASON }}'
          footer: '<{run_url}|View Run>'
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

