[package]
name = "nimiq-spammer"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2021"
description = "Nimiq's Rust client"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]
exclude = ["db", "peer_key.dat"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
futures = "0.3"
lazy_static = { version = "1.4", optional = true }
log = { package = "tracing", version = "0.1", features = ["log"] }
prometheus = { version = "0.13", features = ["process"], optional = true }
rand = "0.8.5"
tokio = { version = "1.16", features = ["rt-multi-thread", "time", "tracing"] }
structopt = { version = "0.3", features = ["paw"] }
warp = { version = "0.3.2", optional = true }

nimiq-block = { path = "../primitives/block" }
nimiq-blockchain = { path = "../blockchain" }
nimiq-keys = { path = "../keys" }
nimiq-mempool = { path = "../mempool" }
nimiq-primitives = { path = "../primitives", features = ["coin", "networks"] }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-transaction-builder = { path = "../transaction-builder" }

[dependencies.nimiq]
package = "nimiq-lib"
path = "../lib"
version = "0.1"
features = ["validator", "rpc-server", "deadlock", "logging", "wallet", "panic"]

[features]
metrics = ["lazy_static", "prometheus", "warp"]
